<?xml version="1.0"?>
<package>
  <name>mujoco_ros_utils</name>
  <version>0.0.0</version>
  <description>The mujoco_ros_utils package</description>

  <maintainer email="chou@jsk.imi.i.u-tokyo.ac.jp">chou</maintainer>

  <license>BSD</license>

  <author>Moju Zhao</author>

  <buildtool_depend>catkin</buildtool_depend>

  <build_depend>mujoco</build_depend>

  <run_depend>blender</run_depend>
  <run_depend>mujoco</run_depend>

</package>
